### ISSUE TITLE
Make specific 1 2 3 choices with checkboxes

### ISSUE THREAD

**Issue by katjam** [Incidentallyb/vector#111]
## User story & Acceptance criteria
Trello card: https://trello.com/c/WhrXMYDR/70-sprint-catch-up-15-oct-2020-3pm

### Implementation plan
- [x] Render checkboxes and renderButtons functions in message view
- [x] checkbox & submit
- [x] fix formatting - giant headers 
- [x] scoring only cares about the number of choices, but we care about actual

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
