### ISSUE TITLE
Set up netlify CMS for all types of content

### ISSUE THREAD

**Issue by katjam** [Incidentallyb/vector#115]
## User story & Acceptance criteria
Trello card: https://trello.com/c/Ciiu946o/21-v-as-the-lab-collective-i-need-to-be-able-to-make-simple-edits-to-the-content-in-case-i-find-mistakes-or-contextual-circumstance

https://trello.com/c/xtdknAgk/106-vvv-as-the-lab-collective-i-need-to-be-able-to-make-simple-edits-to-the-content-in-case-i-find-mistakes-or-contextual-circumstan

### Implementation plan
- [x] emails #117 
- [x] messages #125 
- [x] do not require all fields #136
- [x] socials

Carded for later
- [x] docs #168 
- [ ] Improve by making data types for choices & scoring #78 
- [ ] Improve by making relational authors with image see also #161 for images in emails & socials

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
