### ISSUE TITLE
More doc/pdfs in bio storyline

### ISSUE THREAD

**Issue by katjam** [Incidentallyb/vector#118]
## User story & Acceptance criteria
Trello card: https://trello.com/c/t11v5rfj/72-sprint-catch-up-19-oct-3pm

### Implementation notes
Should be triggering extra docs in bio story. When they choose bio as first choice the extra docs should be triggered.

### Implementation plan
- [x] Add stem cell vs bio bank choice docs triggered init|start|bio https://drive.google.com/file/d/1bpJtkBYfNNZQM641Mvotj5WTgoBAyOyX/view?usp=sharing https://drive.google.com/file/d/1uedP4nUDzUpPHnXVszwHFKI0IzEA_n3B/view?usp=sharing 
- [x] Copy change: original bio doc should be Bio matter - title needs changing
- [x] Check they are flagged as new docs
- [x] Reduce font-size of document headers, consider using title fields for casing

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
