### ISSUE TITLE
Better styles for documents - As a participant I need to go to the doc store and see appealing uniform content

### ISSUE THREAD

**Issue by katjam** [Incidentallyb/vector#150]
https://trello.com/c/zzbLSIR6/47-vvv-as-a-research-animal-i-want-participants-to-feel-my-presence-in-the-room-so-that-i-feel-more-immersed-in-the-experience

And also https://trello.com/c/RHCuy3iq/104-vvv-as-a-player-i-want-the-look-and-feel-of-the-app-to-be-aesthetic-feel-modern-and-make-sense-in-terms-of-use-and-immersion

- [x] Better styling on documents and accessible content
- [ ] (ee) As a participant deciding on an animal model I need more dynamic delivery of information and clear examples of their use
- [ ] (eee) Video animal profiles in document section. Info-mmercials for animals people can go back to check in document sections (need more theatricality for people to feel involved)

### Implementation plan
- [ ] Decode fields Content.elm
- [ ] Display content in Views/Document.elm
- [ ] Match the styling of the output to the slide plans
- [ ] Make sure the semantics/accessibility are correct
