### ISSUE TITLE
Get message content from markdown

### ISSUE THREAD

**Issue by katjam** [Incidentallyb/vector#16]
## User story & Acceptance criteria
Trello card: https://trello.com/c/Ciiu946o/21-v-as-the-lab-collective-i-need-to-be-able-to-make-simple-edits-to-the-content-in-case-i-find-mistakes-or-contextual-circumstance

### Implementation notes
Proof of concept during setup

### Implementation plan
- [x] Author content in markdown dc31103
- [x] Import message content into Elm
- [x] decode list of messages Right now we have single message decoder we want Dict String Message

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
