### ISSUE TITLE
Sass and bootstrap stubs

### ISSUE THREAD

**Issue by Nikomus** [Incidentallyb/vector#21]
## User story & Acceptance criteria
Trello card: https://trello.com/c/yMSYXaHP/10-vvv-as-a-player-i-need-to-have-access-to-emails-documents-info-from-bio-core-tweets-and-messages-that-have-been-revealed-thus-fa
### Implementation plan
- [x] Get sass compiling
- [x] Get hot reloading working
- [x] Compile Bootstrap from source sass and pull in where we want it

### Stage 2
- [x] Do the webpack config for production

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
