### ISSUE TITLE
persistent access to email, messages, twitter, docs

### ISSUE THREAD

**Issue by Nikomus** [Incidentallyb/vector#23]
## User story & Acceptance criteria
Trello card: {{link}}

### Implementation plan
- [x] Adding icons from https://package.elm-lang.org/packages/jasonliang512/elm-heroicons/latest/ 
( had to use elm install jasonliang-dev/elm-heroicons instead )
- [x] Create base HTML style
- [x] Create desktop style
- [x] Create navigation area

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
