### ISSUE TITLE
Decoders for all content types

### ISSUE THREAD

**Issue by Nikomus** [Incidentallyb/vector#31]
## User story & Acceptance criteria
Trello card: {{link}}

### Implementation plan
- [x] Decode social & emails https://github.com/TheLabCollective/vector/pull/52
- [x] Map decoded data to document views
- [x] Map decoded data to message views
- [x] Map decoded data to social views
- [x] KRIS: Map decoded data to email views

merge to feature/31-content-decoders

our branches are
- feature/31-content-decoders-kris
- feature/31-content-decoders-katja

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
