### ISSUE TITLE
Content visibility activated mechanic

### ISSUE THREAD

**Issue by Nikomus** [Incidentallyb/vector#33]
### Implementation plan
- [x] update markdown with values for choices
- [x] make buttons register choices
- [x] Use choices to filter content data
- [x] step solution for couple of awkward places
- [x] Move game data modeling out of main

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
