### ISSUE TITLE
Scoring mechanic

### ISSUE THREAD

**Issue by Nikomus** [Incidentallyb/vector#34]
## User story & Acceptance criteria
Trello card: https://trello.com/c/Dx9UbTxc/14-vvv-as-a-player-i-need-to-see-my-aggregated-score-after-each-act-throughout-the-gameplay-so-that-i-can-be-aware-of-my-progress

### Implementation notes
Show delta (change up/down) since last score

playing offline, the world is not established for you by facilitator - so this is even more important

In content of result summary: "you decided to do this, therefore increased harm"

 - Assumption - Scoring can be worked out from 'set of choices' - or does it also depend on order revealed in? Depends on order but that would be a different choice technically. Keep track of choices rather than content since they dictate score & need to be reported on. Use choices to calculate content & hopefully the scoring also.

### Implementation plan
- [x] Scoring system storage (money, harm, success)

### Alpha needs
 - [ ] The score is presented to player at end of each phase in a message
 - [ ] as-a-player-i-need-to-not-understand-the-scoring-mechanics-so-that-i-can-fully-engage-in-the-content-rather-than-be-tempted-to-g

https://docs.google.com/spreadsheets/d/1HioPn8oprYQQfbaYXuEKYIgh_pKp2ODSSbjplOnabxY/edit?usp=sharing

Round 1: 
https://drive.google.com/file/d/1qhGYvF0Dfl-oc3VucxBiqYOa0YbDS4RW/view?usp=sharing

Round 2: https://drive.google.com/file/d/1j8eapQN_6ywCrmBw1tagpX9WTbNqAwWa/view?usp=sharing

Final Results:
https://drive.google.com/file/d/1gMZ3q-xtOsV_trtYUgkuQaGsRNPV8RBZ/view?usp=sharing

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
