### ISSUE TITLE
Add scoring values to content markdown

### ISSUE THREAD

**Issue by Nikomus** [Incidentallyb/vector#35]
## User story & Acceptance criteria
Trello card: {{link}}

### Implementation plan
- [x] scoring for macaques
- [x] scoring for pigs
- [x] scoring for mice
- [x] scoring for fish

Bio will be done same time as content #76 

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
