### ISSUE TITLE
Choose a team name

### ISSUE THREAD

**Issue by kris-sum** [Incidentallyb/vector#61]
## User story & Acceptance criteria
Trello card: https://trello.com/c/xwIUhNHC/9-v-as-a-player-participating-in-a-group-session-i-need-to-be-able-to-choose-a-team-name-so-that-a-facilitator-or-performer-can-re

### Implementation notes

- A player can select a name for their team (can be by compliance in a live group)

- There is a list of team names
- Data can be tagged with timestamp to uniquify - might belong with As a performer or facilitator running a multiplayer session I need to be able to tag my session(s) with a label so that the stats can be viewed together

### Implementation plan

- [x] A method for assigning or choosing a team name before gameplay starts (as first message

### acceptance

- [x] I can choose (or be assigned?) a team name at the start of the game.
- [x] There are at least 10 choices of name
