### ISSUE TITLE
Add routing stubs

### ISSUE THREAD

**Issue by katjam** [Incidentallyb/vector#7]
## User story & Acceptance criteria
Trello card: https://trello.com/c/yMSYXaHP/10-vvv-as-a-player-i-need-to-have-access-to-emails-documents-info-from-bio-core-tweets-and-messages-that-have-been-revealed-thus-fa

### Implementation notes
This is just the routing wiring, no styling, copy etc

### Implementation plan
- [x] Implement `Browser.application`
- [x] Define `routeFromUrl` helper
- [x] Define `Route` custom types and `routeParser`

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
