### ISSUE TITLE
Add minimum required assets for PWA

### ISSUE THREAD

**Issue by katjam** [Incidentallyb/vector#8]
## User story & Acceptance criteria
Trello card(s): 
- https://trello.com/c/X8K5dtVe/26-as-a-player-i-do-not-need-to-be-able-to-download-the-app-from-play-or-app-stores-because-i-can-make-a-shortcut-and-use-it-in-my
- https://trello.com/c/mayKh491/23-as-a-player-or-performer-i-need-to-be-able-to-use-the-app-offline-in-case-i-have-a-bad-or-no-internet-connection

### Implementation notes
Follow recommendations for minimal config. We can tweak caching & service worker later.

Be wary of the offline-features during development, as asset-caching can interfere with the file-changes you’re making. These can be toggled on/off in Chrome(ium)-devtools.

### Implementation plan
- [x] Add some icons
- [x] Add a manifest.json file to specify the app-stuff
- [x] Add a service-worker to handle interception of network-requests, enabling offline storage.
- [ ] See what lighthouse has to say

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
