### ISSUE TITLE
Content documentation

### ISSUE THREAD

**Issue by katjam** [Incidentallyb/vector#94]
## User story & Acceptance criteria
As a person editing content with less coding knowledge I need some documentation about editing content so that I can make small change.

### Implementation plan
- [ ] Document how content works
- [ ] Document how scoring works
- [ ] Document how display triggers work

For **Frontend** stories - remember to consider **accessibility** & **responsiveness**
