### ISSUE TITLE
Scoring bugs

### ISSUE THREAD

**Issue by katjam** [Incidentallyb/vector#97]
## Description
Get scoring

## Steps to reproduce
1. progress through a storyline
1. see that scores don;t all add up correctly
1. see that success and harm scores appear to be swapping

## Implementation plan
- [ ] Better scoring function using keys from dict - once alphabetical - use lists
- [ ] See notes on `branchingContentistKeyedByTriggerChoice`
- [ ] why is harm and success score swapped?
- [x] as per suggestion #98: I think the "updateSuccessScore/updateScore" functions should be the same - they can all use the =(set) syntax. Reduces duplication.

## Bugs
- [x] `no-more-macaques` email not firing (missing space after -) 
- [x] pig vs pigs

## Platform (if relevant)
What device and browser were you using?
